# Generated by Django 4.2.16 on 2026-08-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Miembro",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefono", models.CharField(max_length=20)),
                ("fecha_nacimiento", models.DateField()),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "peso_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("estatura_cm", models.IntegerField(blank=True, null=True)),
                (
                    "huella_biometrica_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("estado_activo", models.BooleanField(default=True)),
                ("notas_medicas", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
