# Generated by Django 4.2.16 on 2026-08-12 15:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("gym_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("capacidad_maxima", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TipoMembresia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("costo", models.DecimalField(decimal_places=2, max_digits=8)),
                ("dias_duracion", models.IntegerField(default=30)),
            ],
        ),
        migrations.RemoveField(
            model_name="miembro",
            name="estatura_cm",
        ),
        migrations.RemoveField(
            model_name="miembro",
            name="fecha_nacimiento",
        ),
        migrations.RemoveField(
            model_name="miembro",
            name="fecha_registro",
        ),
        migrations.RemoveField(
            model_name="miembro",
            name="huella_biometrica_id",
        ),
        migrations.RemoveField(
            model_name="miembro",
            name="notas_medicas",
        ),
        migrations.RemoveField(
            model_name="miembro",
            name="peso_kg",
        ),
        migrations.RemoveField(
            model_name="miembro",
            name="telefono",
        ),
        migrations.AlterField(
            model_name="miembro",
            name="apellidos",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="Suscripcion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField(default=django.utils.timezone.now)),
                ("fecha_fin", models.DateField()),
                ("activa", models.BooleanField(default=True)),
                (
                    "miembro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suscripciones",
                        to="gym_core.miembro",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="gym_core.tipomembresia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroAcceso",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_hora_entrada",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_hora_salida", models.DateTimeField(blank=True, null=True)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gym_core.area",
                    ),
                ),
                (
                    "miembro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accesos",
                        to="gym_core.miembro",
                    ),
                ),
            ],
        ),
    ]
