# Generated by Django 5.2.17 on 2026-08-13 21:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_core", "0002_area_tipomembresia_remove_miembro_estatura_cm_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="area",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Área",
                "verbose_name_plural": "Áreas",
            },
        ),
        migrations.AlterModelOptions(
            name="miembro",
            options={
                "ordering": ["apellidos", "nombre"],
                "verbose_name": "Miembro",
                "verbose_name_plural": "Miembros",
            },
        ),
        migrations.AlterModelOptions(
            name="registroacceso",
            options={
                "ordering": ["-fecha_hora_entrada"],
                "verbose_name": "Registro de acceso",
                "verbose_name_plural": "Registros de acceso",
            },
        ),
        migrations.AlterModelOptions(
            name="suscripcion",
            options={
                "ordering": ["-fecha_inicio"],
                "verbose_name": "Suscripción",
                "verbose_name_plural": "Suscripciones",
            },
        ),
        migrations.AlterModelOptions(
            name="tipomembresia",
            options={
                "ordering": ["costo"],
                "verbose_name": "Tipo de membresía",
                "verbose_name_plural": "Tipos de membresía",
            },
        ),
        migrations.AddField(
            model_name="area",
            name="descripcion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="miembro",
            name="estatura_cm",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="miembro",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="miembro",
            name="fecha_registro",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 8, 13, 21, 48, 46, 615624, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="miembro",
            name="notas_medicas",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="miembro",
            name="peso_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="miembro",
            name="telefono",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="tipomembresia",
            name="descripcion",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="area",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="nombre",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="miembro",
            name="estado_activo",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
        migrations.AlterField(
            model_name="miembro",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="registroacceso",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accesos",
                to="gym_core.area",
            ),
        ),
        migrations.AlterField(
            model_name="registroacceso",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="suscripcion",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="suscripcion",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="suscripciones",
                to="gym_core.tipomembresia",
                verbose_name="Tipo de membresía",
            ),
        ),
        migrations.AlterField(
            model_name="tipomembresia",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="tipomembresia",
            name="nombre",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
